-- OpsIntel incident investigation analytics
-- Compare incident-period behavior with the server's normal baseline.

WITH baseline AS (
    SELECT
        SERVER_NAME,
        AVG(CPU_PCT) AS BASELINE_CPU,
        AVG(MEMORY_PCT) AS BASELINE_MEMORY,
        AVG(RESPONSE_MS) AS BASELINE_RESPONSE_MS,
        AVG(ERROR_RATE_PCT) AS BASELINE_ERROR_RATE,
        AVG(HTTP_5XX) AS BASELINE_5XX
    FROM OPSINTEL.SERVICE_METRICS
    WHERE SERVER_NAME = 'web-03'
      AND NOT (
          EVENT_TIME >= TIMESTAMP '2026-09-12 14:30:00'
          AND EVENT_TIME < TIMESTAMP '2026-09-12 14:40:00'
      )
    GROUP BY SERVER_NAME
),

incident AS (
    SELECT
        SERVER_NAME,
        AVG(CPU_PCT) AS INCIDENT_CPU,
        AVG(MEMORY_PCT) AS INCIDENT_MEMORY,
        AVG(RESPONSE_MS) AS INCIDENT_RESPONSE_MS,
        AVG(ERROR_RATE_PCT) AS INCIDENT_ERROR_RATE,
        AVG(HTTP_5XX) AS INCIDENT_5XX
    FROM OPSINTEL.SERVICE_METRICS
    WHERE SERVER_NAME = 'web-03'
      AND EVENT_TIME >= TIMESTAMP '2026-09-12 14:30:00'
      AND EVENT_TIME < TIMESTAMP '2026-09-12 14:40:00'
    GROUP BY SERVER_NAME
)

SELECT
    i.SERVER_NAME,

    ROUND(b.BASELINE_CPU, 2) AS BASELINE_CPU,
    ROUND(i.INCIDENT_CPU, 2) AS INCIDENT_CPU,
    ROUND(i.INCIDENT_CPU - b.BASELINE_CPU, 2) AS CPU_DELTA,

    ROUND(b.BASELINE_MEMORY, 2) AS BASELINE_MEMORY,
    ROUND(i.INCIDENT_MEMORY, 2) AS INCIDENT_MEMORY,
    ROUND(i.INCIDENT_MEMORY - b.BASELINE_MEMORY, 2) AS MEMORY_DELTA,

    ROUND(b.BASELINE_RESPONSE_MS, 2) AS BASELINE_RESPONSE_MS,
    ROUND(i.INCIDENT_RESPONSE_MS, 2) AS INCIDENT_RESPONSE_MS,
    ROUND(i.INCIDENT_RESPONSE_MS / NULLIF(b.BASELINE_RESPONSE_MS, 0), 2)
        AS RESPONSE_MULTIPLIER,

    ROUND(b.BASELINE_ERROR_RATE, 2) AS BASELINE_ERROR_RATE,
    ROUND(i.INCIDENT_ERROR_RATE, 2) AS INCIDENT_ERROR_RATE,

    ROUND(b.BASELINE_5XX, 2) AS BASELINE_5XX,
    ROUND(i.INCIDENT_5XX, 2) AS INCIDENT_5XX

FROM baseline b
JOIN incident i
    ON b.SERVER_NAME = i.SERVER_NAME;
