-- OpsIntel database schema
-- Infrastructure incident investigation dataset

CREATE SCHEMA IF NOT EXISTS OPSINTEL;

CREATE TABLE IF NOT EXISTS OPSINTEL.SERVICES (
    SERVICE_ID VARCHAR(100),
    SERVER_NAME VARCHAR(100),
    SERVICE_NAME VARCHAR(100),
    ENVIRONMENT VARCHAR(30),
    REGION VARCHAR(50),
    OWNER_TEAM VARCHAR(100),
    CREATED_AT TIMESTAMP
);

CREATE TABLE IF NOT EXISTS OPSINTEL.SERVICE_METRICS (
    EVENT_TIME TIMESTAMP,
    SERVER_NAME VARCHAR(100),
    SERVICE_NAME VARCHAR(100),
    CPU_PCT DECIMAL(6,2),
    MEMORY_PCT DECIMAL(6,2),
    DISK_PCT DECIMAL(6,2),
    NETWORK_MBPS DECIMAL(12,2),
    RESPONSE_MS DECIMAL(12,2),
    ERROR_RATE_PCT DECIMAL(6,2),
    HTTP_5XX INTEGER,
    REQUESTS_PER_MIN INTEGER,
    HEALTH_STATUS VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS OPSINTEL.INCIDENT_EVENTS (
    EVENT_TIME TIMESTAMP,
    SERVER_NAME VARCHAR(100),
    SERVICE_NAME VARCHAR(100),
    EVENT_TYPE VARCHAR(50),
    SEVERITY VARCHAR(20),
    EVENT_MESSAGE VARCHAR(500)
);
